Telephony: Fix NoClassDefFoundError in TelecomAccountRegistry
04-02 03:43:07.029  3804  3804 E AndroidRuntime: FATAL EXCEPTION: main
04-02 03:43:07.029  3804  3804 E AndroidRuntime: Process: com.android.phone, PID: 3804
04-02 03:43:07.029  3804  3804 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/codeaurora/internal/IExtTelephony$Stub;
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at com.android.services.telephony.TelecomAccountRegistry.isRadioInValidState(TelecomAccountRegistry.java:1382)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at com.android.services.telephony.TelecomAccountRegistry.setupAccounts(TelecomAccountRegistry.java:1340)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at com.android.services.telephony.TelecomAccountRegistry.access$1000(TelecomAccountRegistry.java:81)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at com.android.services.telephony.TelecomAccountRegistry$1.onSubscriptionsChanged(TelecomAccountRegistry.java:819)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at android.telephony.SubscriptionManager$OnSubscriptionsChangedListener$OnSubscriptionsChangedListenerHandler.handleMessage(SubscriptionManager.java:945)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
04-02 03:43:07.029  3804  3804 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: org.codeaurora.internal.IExtTelephony$Stub
04-02 03:43:07.029  3804  3804 E AndroidRuntime: 	... 11 more